name: Manual Kubernetes Secret Creation

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  id-token: write
  contents: read

jobs:
  create-secret:
    name: Create Kubernetes Secret
    runs-on: ubuntu-latest
    env:
      CLUSTER_ID: ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}

    - name: Authenticate with DigitalOcean
      run: doctl auth init --access-token ${{ secrets.DIGITALOCEAN_API_TOKEN }}

    - name: Fetch and Configure Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        doctl kubernetes cluster kubeconfig save "$CLUSTER_ID"

    - name: Verify Kubernetes Connection
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: Create Kubernetes Secret
      run: |
        kubectl create secret generic db-credentials \
          --from-literal=DATABASE_URL="${DATABASE_URL}" \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Verify Secret Creation
      run: kubectl get secret db-credentials -o yaml
